### ISSUE TITLE
Playing web radios

### ISSUE THREAD

**Issue by sergionader** [vabatta/omx-manager#1]
Hello,

Congrats for you work. Really nice.

I have a question: 
This works perfectly:
`omx.play('thelookoflove.mp3')`

But I can't make it to work:
`omx.play('http://199.180.72.6')`
though I can play this very same URL at the comand line with
`omxplayer http://199.180.72.6`

Am I missing something? Any recommendation?

Best regards,

Sergio

**Comment by vabatta** [comment]
Hi Sergio,

what you're saying is right. `omx-manager` assume that every string passed is a file. I should implement a check for stream.

**Comment by sergionader** [comment]
Thank you. Let us know when have news. 

Best regards,

Sergio

**Comment by vabatta** [comment]
I should completely rewrite the library to handle this, because it's all based on using video files (for example the play and pause function).

**Comment by vabatta** [comment]
Now included in version `0.1.0`.
