### ISSUE TITLE
Multiple instances of omxplayer 

### ISSUE THREAD

**Issue by meiti** [vabatta/omx-manager#4]
Hi

I want to play two video files simultaneously and side by side. How can I create multiple instances of omxplayer.

The following code does not work:

omx.play('videos/1.mp4', {'--loop': true, '--win' : "0 0 960 540"});
omx.play('videos/2.mp4', {'--loop': true, '--win' : "960 0 1920 540"});

**Comment by vabatta** [comment]
Hi, omx player is meant to be a static class. You can use the forked version https://github.com/rgjamkhedkar/omx-manager to get rid of that (maybe, could be a little outdated). I will do a rework of this library one day.

**Comment by vabatta** [comment]
Now included with version `0.1.0`.
