### ISSUE TITLE
OmxManager is not a constructor

### ISSUE THREAD

**Issue by PtrBld** [vabatta/omx-manager#5]
Hi,

when I add these two lines from the readme to my file:
`var OmxManager = require('omx-manager');
var manager = new OmxManager(); // OmxManager`

It just says "OmxManager is not a constructor" and ends execution.
Can you please help me with this?

**Comment by vabatta** [comment]
Yes, as I migrated to ES6, the import should be `var OmxManager = require('omx-manager').default;`.
Nevermind, I switched back to old import with the version `0.1.3`. 
Run `$> npm update` and you should be good!
