### ISSUE TITLE
Stop function didn't work on looping videos

### ISSUE THREAD

**Issue by zapbuild** [vabatta/omx-manager#6]
I want to play multiple videos in loop. I'm using it like below.
`var OmxManager = require('omx-manager');`
`var manager = new OmxManager(); // OmxManager`
`var omx = manager.create(videos, {'--loop': true}); // OmxInstance`
`omx.play();`

But when I call `omx.stop();`, It only stop the current video that is playing. It again playing loop by starting with next video. I want to stop the omxplayer loop completely. How it can be possible? 

Thanks for the help!

**Comment by vabatta** [comment]
Should be fixed with `0.1.4`.
